services:
  db:
    container_name: postgres-TBS-ERP
    image: postgres
    environment:
      POSTGRES_USER: razgallah
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: no

networks:
  db:
    driver: bridge

volumes:
  db: